name: "Firebase channels clone"
description: "This is the simple action, that allow you clone channels throw Firebase projects"
author: "Nikita Glukhi <glukhi.nikita@gmail.com>"
branding:
  icon: "book-open"
  color: "green"
inputs:
  project_id:
    description: "The Firebase project that contains the Hosting site to which you want to clone"
    required: true
  channel_id:
    description: "The ID of the channel that you want to clone"
    required: true
  target_project_id:
    description: "The Firebase project that contains the Hosting site where want to clone your channel"
    required: true
  target_channel_id:
    description: "The ID of the channel where you want to clone your channel"
    required: true
  firebase_service_account:
    description: "This is a service account JSON key"
    required: true
  firebase_tools_version:
    description: "The version of 'firebase-tools'. If not specified, defaults to 'latest'"
    required: false
runs:
  using: "node20"
  main: "bin/action.min.js"
